class Config:
    GRID_WIDTH = 20
    GRID_HEIGHT = 20
    MAX_HOLE_INDENT = 10
    MIN_HOLE_INDENT = 5
    MIN_PATH_LENGTH = 15
    MIN_BOOST_PAD_COUNT = 1
    MAX_BOOST_PAD_COUNT = 3
    MIN_COMPLICATE = 1
    MAX_COMPLICATE = 4
